### ISSUE TITLE
v2.15 version release

### ISSUE THREAD

**Issue by wandenberg** [savonrb/savon#1000]
Hello. Any idea when a new version will be released?
The 2.14.0 is preventing the update of other gems like wasabi.

**Comment by pcai** [comment]
Thanks for your patience.

I'm trying to get a release out this weekend, but keep encountering unexpected interactions and incompatibilities with the various versions of savon, httpi, wasabi, and their dependents (mainly the different versions of ruby, openssl, and rack). I will try to sort through them and make some more forward progress over the next couple days.

You should note that I recently discovered wasabi 5.0 is currently not compatible with any version of savon, and probably requires some more coordination work due to the ongoing efforts in https://github.com/savonrb/savon/pull/998

**Comment by pcai** [comment]
resolved in https://github.com/savonrb/savon/releases/tag/v2.15.0
