### ISSUE TITLE
Rollback Wasabi and HTTPi major version bumps

### ISSUE THREAD

**Issue by tvdeyen** [savonrb/savon#1004]
Savon 2.15 allowed to install latest `httpi` and `wasabi` gems. Both have breaking changes. 

Since this is a minor version update, these major version updates come very unexpected.

Issues we encountered are:

- https://github.com/savonrb/httpi/issues/244
- https://github.com/savonrb/wasabi/issues/118

only to name a few.

Please consider to release a new 2.16 that pins `httpi` and `wasabi` back to working releases and release the major version updates as a v3.

Thanks

**Comment by pcai** [comment]
Thanks for the suggestion; I agree this would be the most stable and conservative approach, but IMHO currently it is not feasible - given the available capacity - to support multiple concurrent releases of savon and supporting libraries (sekken and savon v3 being examples of this). Right now its mostly just me doing my best to manage releases with a few hours a month; I'm open to changing my mind on this if the situation changes.

So by default, the latest savon is intended to work with the contemporary releases of wasabi and httpi, even if they have major version bumps (usually due to strict interpretation of semver). If they don't - it's a bug to be fixed, not a permanent branch in the support matrix which would quickly become unsustainable -- especially once we add ruby versions into the mix. 

As you've already noted, applications can opt for a more conservative stance by locking the versions of these dependencies in the Gemfile.
