### ISSUE TITLE
Savon set multiple namespaces

### ISSUE THREAD

**Issue by jmarquesCC** [savonrb/savon#376]
Hi all,

I'm trying to invoke a webservice (with Savon version 2) and i need to inject some additional namespaces to my Envelope. 

Something like:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:add="http://schemas.xmlsoap.org/ws/2003/03/addressing" 
xmlns:newNamespace1="http://someURL.pt/Test1" 
xmlns:newNamespace2="http://someURL.pt/Test2" 
xmlns:newNamespace3="http://someURL.pt/Test3"
```

My current code is:

```
client = Savon.client do
    wsdl "https://someValidURL?wsdl"

    namespace "http://someURL.pt/Test1" 
    namespace "http://someURL.pt/Test2" 
    namespace "http://someURL.pt/Test3"
end

response = client.call( ...the webservice call... )
```

...but in my request the Savon only puts the last namespace

```
<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:xsns="http://someURL.pt/Test3" 
xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
```

I didn't find any documentation about this :S.

Does anyone have a solution/workaround for this problem??

PS - I notice that the version 1 have this feature (i didn't try yet):

```
 soap.namespaces["xmlns:g2"] = "http://g2.example.com"
```

Should i migrate to version 1?

**Comment by pjdjr** [comment]
Are multiple namespaces supposed to be working now in the current version of Savon 2? I could be doing something wrong as there is little documentation on how to set this up, but it isn't working for me.

**Comment by pjdjr** [comment]
Below is essentially the SOAP call I'm trying to make. I simplified it a bit for readability and obscured it somewhat since this is not my code to publicly share. I think I am properly setting up 4 namespaces, but other than the opening `Envelope` tag, the output of the `build` method call uses the `tns` namespace exclusively (this is my primary namespace, that I declared as `zz` and which is built as `tns`). I have indicated in the code below where different namespaces should be invoked.

Also, if I perform the same SOAP call without defining namespaces, I get a virtually identical SOAP message. The structure of the body is identical, using namespace `tns` throughout. The only difference is in the opening `Envelope` tag: instead of listing 4 namespaces in the opening tag, only one is listed (the namespace I declared as `zz`, as expected).

Let me know if you think I'm doing something wrong or if you think there is a bug.

Thanks!

```
namespaces = { 'xmlns:con' => 'http://www.zz.com/con', 'xmlns:con1' => 'http://www.zz.com/con1', 'xmlns:con2' => 'http://www.zz.com/con2', xmlns:zz="http://zz.com/zz" }
client = Savon.client(wsdl: 'http://myserver.com/zzSOAP/wsdl/zz.wsdl', pretty_print_xml: true, namespaces: namespaces)

# I omitted the actual message as it is lengthy and does not explicitly involve namespaces.
# The ops.build output is the important part.
message = { **Savon-formatted message here** }

ops = client.operation(:zz_soap_call)
ops.build(:message => message)
```

Output:

```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://zz.com/zz" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:con="http://www.zz.com/con" xmlns:con1="1" xmlns:con2="http://www.zz.com/con2">
    <env:Body>
        <tns:zzSoapCalls>
            <tns:zzSoapCall>
                <!-- Everything in zzcon should be "con" namespace (but is not)-->
                <tns:zzcon id="123456" emailTemplate="Test">
                    <tns:email>pjdjr@zzmail.com</tns:email>
                    <tns:subject>Greetings</tns:subject>
                    <tns:body>Hi there</tns:body>
                    <tns:sender>
                        <tns:firstName>Joe</tns:firstName>
                        <tns:lastName>Sender</tns:lastName>
                        <tns:email>jsender@zzmail.com</tns:email>
                    </tns:sender>
                </tns:zzcon>
                <!-- Everything in zzcon1 should be "con1" namespace (but is not)-->
                <tns:zzcon1 id="123456">
                    <tns:recipientList>
                        <tns:recipient name="Recipient">
                            <tns:firstName>PJ</tns:firstName>
                            <tns:lastName>DuJouR</tns:lastName>
                            <tns:eMail>pjdjr@zzmail.com</tns:eMail>
                        </tns:recipient>
                    </tns:recipientList>
                </tns:zzcon1>
                <!-- Everything in zzcon2 should be "con2" namespace (but is not)-->
                <tns:zzcon2 id="123456">
                    <tns:docList>
                        <tns:docId required="true">3959299</tns:docId>
                    </tns:docList>
                </tns:zzcon2>
            </tns:zzSoapCall>
        </tns:zzSoapCalls>
    </env:Body>
</env:Env

**Comment by pjdjr** [comment]
OK, my coworker seems to have figured this out. Our folly was in my comment above where I have "`message =`". I wrote, "I omitted the actual message as it is lengthy and does not explicitly involve namespaces." In actuality we have discovered that in defining each element of the message we need to specify the namespace. So, instead of 

`:email => 'jsender@zzmail.com'`

the correct format is

`'con:email' => 'jsender@zzmail.com'`.

Defining my namespaces in this manner, I did notice that the SOAP message sent to the server seems to be slightly different when calling via 
`client.call(:zz_soap_call, :message => message)`
vs
`client.call(:zz_soap_call, :xml => myxml)`,
i.e., using Savon formatting of my message vs merely pasting in XML. With the Savon formatting, the SOAP XML on the server end appears with `tns` as my primary namespace while pasting in the XML preserves the namespace abbreviation I came up with. The SOAP call seems to be successful either way, but there is that slight and seemingly inconsequential difference.
