### ISSUE TITLE
Excon issue with httpi since 2.3.0 (not in 2.2.0)

### ISSUE THREAD

**Issue by fredv** [savonrb/savon#491]
```
Excon::Errors::SocketError: no implicit conversion of OpenSSL::X509::Certificate into String (TypeError)
```

Hey, first up I compliment on the simplicity of savon and love it for the amount of SOAP-pain it hides!

Second, there seems to be a difference how 2.3.0 handles SSL Certificates due to a change in "httpi". Did I miss a change in the savon documentation?

**Comment by julesce** [comment]
Just wanna throw a :+1: to this: "We had success simply using 'httpi', '2.0.2' and 'savon', '2.2.0' for our use-case."

I ran into the same issue as described, and the above suggestion got things fixed for me. Thanks @fredv!

**Comment by josegrad** [comment]
Hi, I'm on Rails (4.2.3), excon (0.45.4), savon (2.11.1), httpi (2.4.1)
Ruby 2.2.1

```
savonConfig = {
		    :endpoint => 'https://webservices.abc/v1/',
		    :env_namespace => :soapenv,
		    :namespace_identifier => :ns,
		    :wsdl => File.open(Rails.root.to_s+'/lib/assets/abc.wsdl', 'rb'),
		    :log_level => :debug,
		    :log => true,
		    #:ssl_verify_mode => :none,
		    :ssl_cert_file => (Rails.root.to_s+'/lib/assets/abc/public.pem').to_s,
		    :ssl_cert_key_file => (Rails.root.to_s+'/lib/assets/aabc/private.pem').to_s,
		    :ssl_cert_key_password => 'abc',
		    :open_timeout => 600,
		    :read_timeout => 600
		}

client = Savon.client(savonConfig)
```
When I try a connection with the commented ssl_verify_mode => :none this comes out:
```
Excon::Errors::SocketError: no implicit conversion of OpenSSL::X509::Certificate into String (TypeError)
```
If that line is in use I get:
```
Excon::Errors::SocketError: SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert handshake failure (OpenSSL::SSL::SSLError)
```

I wasnt sure to open a new thread since this same stuff is discussed here. However the "fixes" seem to be downgrading to quite early versions, which I guess is not a good idea.

Any hints how to correct this problem?



I'm using a p12 cert and broke it down into a public cert and private key. Is it password protected.

**Comment by josegrad** [comment]
Well I got over my problem so far. Excon is loaded by HTTPI if httpclient gem is not present. I added httpclient to my gemfile and now the connection using the p12 cert seems to proceed properly.
