### ISSUE TITLE
wasabi 3.3.1

### ISSUE THREAD

**Issue by anazar** [savonrb/savon#656]
Can you please update the wasabi dependency to 3.3.1?  Currently having mime-types dependency issues.

**Comment by alexkravets** [comment]
+1

**Comment by morgoth** [comment]
same issue here - 3.3.1 removes `mime-types` dependency

**Comment by toncid** [comment]
+1

**Comment by aaronchi** [comment]
+1 Don't understand the reason for this change. wasabi 3.3.1 working fine on pre 2.8

**Comment by ZenCocoon** [comment]
Related to https://github.com/savonrb/savon/issues/651

Would also love this update, currently stopping me to use the public savon gem with Rails 4.1.9 due to `mime-types` dependency

**Comment by arashm** [comment]
same issue

**Comment by areman** [comment]
+1

**Comment by tjarratt** [comment]
Sorry everyone, I took me quite a while to resolve this because I was trying (really, really trying) to find a way to keep the fix we applied back in November and make it backwards compatible. 

Savon v2.10.0 was just released, unlocking Wasabi from v.3.3.0. This should be resolve mime-types dependency issues.
