### ISSUE TITLE
Support for operation overloading

### ISSUE THREAD

**Issue by robbiewareham** [savonrb/savon#669]
I am trying to consume a soap service which contains operation overrides (something I believe is supported but discouraged in Soap 1.1, and not supported in 1.2).

Is Savon supposed to support this scenario? eg.

``` xml
<wsdl:operation name="BarOperation">
<soap:operation soapAction="http://schema.foo.com/BarOperation" style="document"/>
<wsdl:input>
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output>
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="BarOperation">
<soap:operation soapAction="http://schema.foo.com/BarOperationOverload" style="document"/>
<wsdl:input name="BarOperationOverload">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="BarOperationOverload">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
```

There is an issue in the code that when processing the 1st occurrence in Wasabi::Parser 'parse_operations', in that it gets the 2nd occurrence from @port_type_operations.

Obviously, I will not raise this as a bug if Savon is not designed to support overloaded operations

**Comment by tjarratt** [comment]
Hey @robbiewareham thanks for opening this issue. I've never heard of operation overrides before.

While Savon has a concept of the soap version, I don't think it includes this feature. If you're interested in submitting a pull request for this, you might want to start by taking a look at [builder.rb](https://github.com/savonrb/savon/blob/master/lib/savon/builder.rb) which is responsible for building the request XML.

Since you already have a snippet of a WSDL that makes this fail, it shouldn't be too hard to write a failing spec for this behavior (e.g.: when the soap_version is set to 1.1, it allows for overriding). The tricky part would probably be coercing [Wasabi](https://github.com/savonrb/wasabi) (which is responsible for parsing the WSDL) to do the correct thing with the name (or getting Savon to do this after the fact, perhaps).

**Comment by eltonokadabss** [comment]
Having the same problem here @robbiewareham, how did you solve it?

Thanks
