### ISSUE TITLE
XML response Parse error.

### ISSUE THREAD

**Issue by gnium** [savonrb/savon#740]
Hi, i'm having an issue with a big response parsing where i have an xml with about 40k elements. 
the main error begins with:

> Unable to parse response body: "<?xml version=\"1.0\" encoding=\"utf-8\"?>

My call is:

`cnf = YAML::load_file('config/wsc.yml')
      @client ||= Savon.client(
 		wsdl: cnf['wsc']['url'],
 		convert_request_keys_to: :none,
 		log: true,
    open_timeout: 600,
    read_timeout: 600,
    	pretty_print_xml: true
 		)
request = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cot="XXXXXX-XXXXXXX">
             <soapenv:Header/>
             <soapenv:Body>
                <cot:GetCatalog>
                   
                <cot:mixml><![CDATA['+req.to_xml(:root => "GetCatalog",:skip_types => true, :skip_instruct => true)+']]></cot:mixml>
                </cot:GetCatalog>
             </soapenv:Body>
          </soapenv:Envelope>'

 	response = client.call(
		:get_catalog, 
			xml:  request
			)`

Any suggestion about how to find a workaround for this? I suppouse it's about the xml lenght, it's >3mb of text.
Thanks in advance!

**Comment by tjarratt** [comment]
Hey @gnium I'm sorry, but I don't think anyone will be able to help you.

Savon is open source, which means you can use it for free, change it as you like, and do what you will with it. We all have our own jobs, and I'm only doing this in my free time because I feel like it's better to respond with "I'm sorry, but good luck solving your own problems" rather than to let these issues collect.

Good luck!
