### ISSUE TITLE
Always getting Savon::ExpectationError: Unexpected request to the <SOAP operation> operation in tests

### ISSUE THREAD

**Issue by jerryjohnjacob** [savonrb/savon#865]
Whenever I test a failing scenario in RSpec where I expect a SOAP fault, I keep getting the following error:

```
Savon::ExpectationError: Unexpected request to the <SOAP operation> operation
```

Here's the test setup that I have as described at the end of [the docs for testing](http://savonrb.com/version2/testing.html):

```Ruby
fixture = File.read("spec/fixtures/soap_fault.xml")
response = { code: 500, headers: {}, body: fixture }
savon.expects(endpoint).with(message: :any).returns(response)
```

This is what `soap_fault.xml` looks like:

```XML
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
      <soap:Fault>
         <faultcode>soap:Server</faultcode>
         <faultstring>Fault occurred while processing.</faultstring>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

Am I doing something wrong?

**Comment by chrislewis60** [comment]
Same issue here. Did you find a resolution?

**Comment by shiju-d** [comment]
Same issue here, once mock a SoapFault error, then I am receiving Savon::ExpectationError for any further soap requests.

**Comment by jerryjohnjacob** [comment]
@chrislewis60 Sorry, haven't looked at this thread in a long while. Got a notification from the comment posted by @shiju-d. No, I wasn't able to find a solution, and due to a lack of activity here and the need to move on to more pressing matters, I had to pause on this.

**Comment by jaykilleen** [comment]
In my scenario I am getting this error, because I am using minitest but have enabled the `require "savon/mock/spec_helper"` mock spec helper so that I could mock the status'.

I then had a setup and teardown method that mocked and unmocked the request.

This error was then thrown on a test that did not require the mocking.

So, I took the steps (`savon.mock!` and `savon.unmock!`) of the around type methods and put them directly in tests that required mocking to be used.
